#!/usr/bin/perl

# SkyKitteh at github: http://github.com/ollej/skykitteh
# Mojolicious documentation: http://mojolicio.us/
#
# Neat things to add:
# * Revision control, rollback to earlier version.
# * Syntax highlighting
# * Logo - Kitty smiley in cloud?
# * AJAX updating / JSON responses for backend
# * See more in issues on github page. See above.

use warnings;
use strict;
use Mojolicious::Lite;
use File::Slurp qw(read_file write_file);
use Digest::MD5 qw(md5_hex);

get '/' => sub {
	my $self = shift;
	my $code = read_file($0);
        $self->stash('filename' => $0);
	$self->stash('code' => $code);
	$self->stash('checksum', md5_hex($code));
	$self->render('showform');
};

get '/edit/(:filename)' => sub {
	my $self = shift;
        my $filename = $self->stash('filename');
	my $code = read_file($filename, err_mode => 'quiet');
	$self->stash('code' => $code);
	$self->stash('checksum', md5_hex($code));
	$self->render('showform');
};

post '/' => sub {
	my $self = shift;
	my $filename = $self->param('filename');
	my $code = $self->param('code');
	$code =~ s/\r$//gm;

	if (!$filename) {
	    $self->stash('msg' => "Missing filename.");
	    $self->render('error');
	    return;
	}

	my $commit_message = $self->param('commit_message');
	write_file("/tmp/commit_message.txt", $commit_message);
	
	my $oldcode = read_file($filename, err_mode => 'quiet');
	if ($self->param('checksum') ne md5_hex($oldcode)) {
		$self->stash('msg' => "Code has been updated since you loaded the page, the MD5 checksum didn't match.");
		$self->render('error');
		return;
	}
	write_file($filename, { binmode => ':utf8', atomic => 1 }, $code);

        my $status = system("perl skykitteh.t");
	if ($status) {
	    write_file($filename, { binmode => ':utf8', atomic => 1 }, $oldcode);
	    $self->stash('msg' => "Please don't kill SkyKitteh.");
	    $self->render('error');
	    return;
	}

	$self->redirect_to('/');
};

post '/upload' => sub {
    my $self = shift;
    my $file = $self->req->upload('file');
    if (!$file) {
	    $self->stash('msg' => "Upload failed.");
	    $self->render('error');
	    return;
    }
    my $filename = $file->filename;
    $file->move_to('./' . $filename);
    $self->redirect_to('/');
};

get '/motd' => sub {
    my $self = shift;
    my $add = $self->param('add');
    if ($add) {
	store_motd($add);
    }

    my $motd = 'I can haz code nomz?';

    if (open MOTD, '<', 'motd.txt') {
	my @motds = <MOTD>;
	close MOTD;
	if (@motds) {
	    $motd = @motds[time % scalar(@motds)];
	}
    }

    $self->stash('msg' => $motd);
    $self->render('motd');
};

sub store_motd
{
    my ($motd) = @_;

    if (open MOTD, '>>', 'motd.txt') {
	print MOTD $motd."\n";
	close MOTD;
    }
}

app->start;
__DATA__

@@ layouts/default.html.ep
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
 
<head> 
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
	<title><%= title %></title>
	<style type="text/css">
		#header {
			background-image: -webkit-gradient(
				linear,
				left bottom,
				left top,
				color-stop(0.26, #A3A3A3),
				color-stop(0.63, #E8E8E8)
				);
				background-image: -moz-linear-gradient(
				center bottom,
				#A3A3A3 26%,
				#E8E8E8 63%
			);
			height:50px;
			text-align: center;
		}
		h1,a {
		font-family: "Myriad pro", helvetica;
		}
	</style>
</head>
<body>

<div id="header">
	<h1>=^..^= SkyKitteh =^..^=</h1>
</div>


<div align=center>
<a href="/motd"><img src="http://img189.imageshack.us/img189/5056/skykitteh.jpg" border=5 alt="SKYKITTEH!"/></a> <br>
It's a bird!.<p> It's a plane! <p> It's.... SKYKITTEH! <p> ta-ta-ta-taaaaaaa! <p> <p> <span class="blink_tag_considered_harmful">T'was only a flesh wound!</span></div>


<%= content %>
</body>
</html>

@@ error.html.ep
% layout 'default';
% title 'Error';
<h1>Error!</h1>
<p><%= $msg %></p>

@@ motd.html.ep
<%= $msg %>

@@ showform.html.ep
% layout 'default';
% title 'SkyKitteh';

<h2>Edit SkyKitteh</h2>
<span>I can haz code nomz? (<%= $filename %>)</span>
<form action="/" method="post">
	<div style="display: block; padding: 4px">
		<textarea name="code" rows="45" style="font-family: monospace; width: 100%; height: 100%"><%= $code %></textarea>
	</div>
	<input type="hidden" name="filename" value="<%= $filename %>" />
	<input type="hidden" name="checksum" value="<%= $checksum %>" />


	<a href="http://github.com/ollej/skykitteh">http://github.com/ollej/skykitteh</a>

<h2>Upload File:</h2>
<input type="file" name="file" value="" />

<br />
	<h3>Evolushion comment</h3>
<textarea name="commit_message" rows="3" cols="80"></textarea>
<br /><br />
	<input type="submit" name="submit" value="Evolve!" />
</form>

<h2>Files</h2>
<ul>
% my @files = <*>;
% foreach my $f (@files) {
<li><a href="/edit/<%= $f %>"><%= $f %></a></li>
% }
</ul>
